/**
 * Project represents a container for organizing todos.
 *
 * Each project has an isolated todo list. Users can create multiple projects
 * to separate tasks by context (e.g., "SequenceStack", "HomefrontGroup").
 * The active project is tracked in AppSettings and determines which todos
 * are displayed and modified.
 *
 * @example
 * ```typescript
 * const project: Project = {
 *   id: "550e8400-e29b-41d4-a716-446655440000",
 *   name: "SequenceStack",
 *   createdAt: "2025-11-25T10:00:00.000Z"
 * }
 * ```
 */
export interface Project {
  /**
   * Unique identifier for the project.
   *
   * Format: UUID v4 (e.g., "550e8400-e29b-41d4-a716-446655440000")
   * Generated by: crypto.randomUUID() in ProjectStore.create()
   */
  id: string

  /**
   * User-defined project name.
   *
   * Constraints:
   * - Required (non-empty string)
   * - No maximum length (wraps in UI if long)
   * - Unicode characters supported
   * - Can be renamed at any time
   */
  name: string

  /**
   * ISO 8601 timestamp when project was created.
   *
   * Format: YYYY-MM-DDTHH:mm:ss.sssZ (e.g., "2025-11-25T10:00:00.000Z")
   * Generated by: new Date().toISOString() in ProjectStore.create()
   * Timezone: Always UTC (Z suffix)
   */
  createdAt: string
}
