/**
 * Todo represents a single task in the todo list.
 *
 * This is the core data model for the application. All todos have a unique ID,
 * user-entered text, completion status, and creation timestamp.
 *
 * @example
 * ```typescript
 * const todo: Todo = {
 *   id: "550e8400-e29b-41d4-a716-446655440000",
 *   text: "Implement keyboard navigation",
 *   completed: false,
 *   createdAt: "2025-11-22T10:00:00.000Z"
 * }
 * ```
 */
export interface Todo {
  /**
   * Unique identifier for the todo.
   *
   * Format: UUID v4 (e.g., "550e8400-e29b-41d4-a716-446655440000")
   * Generated by: crypto.randomUUID() in TodoStore.add()
   */
  id: string

  /**
   * User-entered task description.
   *
   * Constraints:
   * - Required (non-empty string)
   * - No maximum length
   * - Unicode characters supported
   * - Whitespace-only text rejected by TodoStore.add()
   */
  text: string

  /**
   * Whether the todo is completed.
   *
   * Values:
   * - false: Active todo (default for new todos)
   * - true: Completed todo
   */
  completed: boolean

  /**
   * ISO 8601 timestamp when todo was created.
   *
   * Format: YYYY-MM-DDTHH:mm:ss.sssZ (e.g., "2025-11-22T10:00:00.000Z")
   * Generated by: new Date().toISOString() in TodoStore.add()
   * Timezone: Always UTC (Z suffix)
   */
  createdAt: string
}
